services:
  - type: web
    name: portfolio-backend-bot
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install
    startCommand: node server/src/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
